language: node_js
node_js: "stable"

script: echo "npm test temporarily disabled"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master